version: '3.8'

services:
  web:
    # Use the Dockerfile in the current directory to build the image
    build: .
    # Map the host port 5000 to the container's port 5000
    ports:
      - "5000:5000"
    # Mount the local application code into the container for easy development
    volumes:
      - .:/app
    # Use a custom command to run your cronjob
    command: cron && python app.py